[[colors.indexed_colors]]
color = "0xffffff"
index = 16

[[colors.indexed_colors]]
color = "0xd65d0e"
index = 17

[[colors.indexed_colors]]
color = "0x3c3836"
index = 18

[[colors.indexed_colors]]
color = "0x504945"
index = 19

[[colors.indexed_colors]]
color = "0xbdae93"
index = 20

[[colors.indexed_colors]]
color = "0xebdbb2"
index = 21

[colors.bright]
black = "0x665c54"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xffffff"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x282828"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "0x282828"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xffffff"
yellow = "0xfabd2f"

[colors.primary]
# dracula background compatible with nvim
background = "0x282A36"
# gruvbox background compatible with nvim
# background = "0x323232"
foreground = "0xd5c4a1"

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "iosevka term extended"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "iosevka term extended"
style = "Italic"

[font.normal]
family = "iosevka term extended"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = 40
mods = "Super"

[mouse]
hide_when_typing = true

[window]
dynamic_title = true
opacity = 0.95

[window.padding]
x = 2
y = 2
